### ISSUE TITLE
Cordblood problem

### ISSUE THREAD

**Issue by lopezpower** [immunomethylomics/FlowSorted.Blood.EPIC#1]
I have a small problem
When I try to implement "Blood" everything works as it should as presented below:

> estimateCellCounts2(RGset, compositeCellType="Blood",referencePlatform="IlluminaHumanMethylationEPIC")
snapshotDate(): 2019-06-18
see ?FlowSorted.Blood.EPIC and browseVignettes('FlowSorted.Blood.EPIC') for documentation
downloading 0 resources
loading from cache 
    ‘EH1136 : 1136’
[estimateCellCounts2] Combining user data with reference (flow sorted) data.
[estimateCellCounts2] Processing user and reference data together.
[estimateCellCounts2] Picking probes for composition estimation.
[estimateCellCounts2] Estimating composition.

$counts
                          CD8T       CD4T         NK      Bcell       Mono       Neu
203253050154_R01C01 0.07413502 0.09214088 0.09493901 0.09953795 0.11065832 0.5799489
203253050154_R02C01 0.12170324 0.18408654 0.04288204 0.12617542 0.11154318 0.4641837

However, when I try to implement "CordBlood" I have a following error:

> estimateCellCounts2(RGset, compositeCellType="CordBlood",referencePlatform="IlluminaHumanMethylationEPIC")
[estimateCellCounts2] Consider including 'nRBC' in argument 'cellTypes' for cord blood estimation.
Loading required package: FlowSorted.CordBlood.EPIC
Błąd w poleceniu 'estimateCellCounts2(RGset, compositeCellType = "CordBlood", referencePlatform = "IlluminaHumanMethylationEPIC")':
  Could not find reference data package for compositeCellType 'CordBlood' and referencePlatform 'EPIC' (inferred package name is 'FlowSorted.CordBlood.EPIC')
Dodatkowo: Komunikat ostrzegawczy:
W poleceniu 'library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, ':
  there is no package called ‘FlowSorted.CordBlood.EPIC’

I couldnt find a package called "FlowSorted.CordBlood.EPIC" on the web either. Would you please help me with this? Im not very familiar with this topic

**Comment by lucassalas** [comment]
@lopezpower 
There is no package using that name.
I f you need to estimate cord blood cell composition. Please use  FlowSorted.CordBloodCombined.450k instead. This library will work for 450k and EPIC samples.

See ?IDOLOptimizedCpGsCordBlood to perform the task.

@lucassalas

**Comment by lucassalas** [comment]
Update, from version 1.3.1 the options are now fully integrated see ?estimatesCellCounts2.
If you are using the previous versions please use the old script ?IDOLOptimizedCpGsCordBlood.
